# Generated by Django 5.1.1 on 2024-09-29 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_client_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+79999999999'.", regex='^\\+?7?\\d{9,12}$')]),
        ),
    ]
